-- What is the overall discount rate (average discount per item sold)?
SELECT AVG(item_discount) AS overall_discount_rate
FROM bazar.bazar_csv;

-- Which warehouse has the highest average order value (total sales
-- revenue divided by number of orders)?
SELECT order_warehouse_id, SUM(amount_per_unit * ordered_quantity) / COUNT(order_number) AS avg_order_value
FROM bazar.bazar_csv
GROUP BY order_warehouse_id
ORDER BY avg_order_value DESC
LIMIT 1;

-- What is the total revenue generated by each store?
SELECT store_id, SUM(amount_per_unit * ordered_quantity) AS total_revenue
FROM bazar.bazar_csv
GROUP BY store_id;

-- Identify the top 5 customers (based on total amount spent).
SELECT order_number, SUM(amount_per_unit * ordered_quantity) AS total_amount_spent
FROM bazar.bazar_csv
GROUP BY order_number
ORDER BY total_amount_spent DESC
LIMIT 5;

-- Calculate the month-over-month growth rate of sales revenue
WITH revenue_monthly AS (
    SELECT 
        EXTRACT(YEAR FROM order_date) AS year,
        EXTRACT(MONTH FROM order_date) AS month,
        SUM(amount_per_unit * ordered_quantity) AS total_revenue,
        LEAD(SUM(amount_per_unit * ordered_quantity)) OVER (ORDER BY EXTRACT(YEAR FROM order_date), EXTRACT(MONTH FROM order_date)) AS next_month_revenue
    FROM bazar.bazar_csv
    GROUP BY year, month
)
SELECT 
    year,
    month,
    (next_month_revenue - total_revenue) / total_revenue AS revenue_growth_rate
FROM revenue_monthly;

-- Determine the percentage of orders that were canceled.

SELECT 
    (COUNT(CASE WHEN order_status = 'cancelled' THEN 1 END) * 100.0) / COUNT(order_number) AS canceled_order_percentage
FROM bazar.bazar_csv;




